### ISSUE TITLE
Pod install throws error

### ISSUE THREAD

**Issue by reddo** [emeraldsanto/react-native-encrypted-storage#7]
Added this package to my project and after trying `pod install`, I get the following error:
```
Installing react-native-encrypted-storage (2.0.0)
[!] Unable to determine Swift version for the following pods:

- `react-native-encrypted-storage` does not specify a Swift version and none of the targets (`obfuscated`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```
EDIT: ~Fixed with the workaround from here: https://stackoverflow.com/a/58784154/2083548, but you might still want to look into this.~ The fix did not work

**Comment by emeraldsanto** [comment]
Is this preventing you from using this package it is that simply a warning?

**Comment by emeraldsanto** [comment]
I just tried a fresh install and it cocoapods did not throw any errors. I will still release a patch later tonight to address this.

**Comment by emeraldsanto** [comment]
Fixed in `2.0.1`, you can update your pod :)

**Comment by reddo** [comment]
> Is this preventing you from using this package it is that simply a warning?

Yes, it was preventing me from using it, the ios build failed.

> Fixed in `2.0.1`, you can update your pod :)

I will give it a try in the morning, thanks for looking into this.

**Comment by reddo** [comment]
Still not ok :(
I have a different error now:
```
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
Undefined symbols for architecture x86_64:
  "Foundation._convertErrorToNSError(Swift.Error) -> __C.NSError", referenced from:
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned __C.NSString?, @unowned __C.NSString?, @unowned __C.NSError?) -> () to @escaping @callee_guaranteed (@guaranteed Swift.String?, @guaranteed Swift.String?, @guaranteed Swift.Error?) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "type metadata for Foundation.Data", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "ObjectiveC._convertBoolToObjCBool(Swift.Bool) -> ObjectiveC.ObjCBool", referenced from:
      @objc static react_native_encrypted_storage.RNEncryptedStorage.requiresMainQueueSetup() -> Swift.Bool in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Darwin.noErr.getter : Swift.Int32", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "value witness table for Builtin.UnknownObject", referenced from:
      full type metadata for react_native_encrypted_storage.RNEncryptedStorage in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      full type metadata for __C.CFBooleanRef in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      full type metadata for __C.CFStringRef in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "(extension in Foundation):Swift.Dictionary._bridgeToObjectiveC() -> __C.NSDictionary", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift.Dictionary.init(dictionaryLiteral: (A, B)...) -> [A : B]", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "(extension in Foundation):Swift.String._bridgeToObjectiveC() -> __C.NSString", referenced from:
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned __C.NSString?, @unowned __C.NSString?, @unowned __C.NSError?) -> () to @escaping @callee_guaranteed (@guaranteed Swift.String?, @guaranteed Swift.String?, @guaranteed Swift.Error?) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "static (extension in Foundation):Swift.String._unconditionallyBridgeFromObjectiveC(__C.NSString?) -> Swift.String", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      @objc react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      @objc react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      @objc react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "(extension in Foundation):Swift.String.init(data: __shared Foundation.Data, encoding: (extension in Foundation):Swift.String.Encoding) -> Swift.String?", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "static (extension in Foundation):Swift.String.Encoding.utf8.getter : (extension in Foundation):Swift.String.Encoding", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "type metadata accessor for (extension in Foundation):Swift.String.Encoding", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift.String.init(stringInterpolation: Swift.DefaultStringInterpolation) -> Swift.String", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift.String.init(_builtinStringLiteral: Builtin.RawPointer, utf8CodeUnitCount: Builtin.Word, isASCII: Builtin.Int1) -> Swift.String", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "type metadata for Swift.String", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      lazy protocol witness table accessor for type Swift.String and conformance Swift.String : Swift.StringProtocol in Swift in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      type metadata accessor for (Swift.String, Any) in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "protocol witness table for Swift.String : Swift.Hashable in Swift", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "protocol conformance descriptor for Swift.String : Swift.StringProtocol in Swift", referenced from:
      lazy protocol witness table accessor for type Swift.String and conformance Swift.String : Swift.StringProtocol in Swift in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "protocol witness table for Swift.String : Swift.TextOutputStreamable in Swift", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "protocol witness table for Swift.String : Swift.CustomStringConvertible in Swift", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "(extension in Foundation):Swift.StringProtocol.data(using: (extension in Foundation):Swift.String.Encoding, allowLossyConversion: Swift.Bool) -> Foundation.Data?", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift.DefaultStringInterpolation.appendInterpolation<A where A: Swift.CustomStringConvertible, A: Swift.TextOutputStreamable>(A) -> ()", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift.DefaultStringInterpolation.appendLiteral(Swift.String) -> ()", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift.DefaultStringInterpolation.init(literalCapacity: Swift.Int, interpolationCount: Swift.Int) -> Swift.DefaultStringInterpolation", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift._allocateUninitializedArray<A>(Builtin.Word) -> ([A], Builtin.RawPointer)", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "Swift._bridgeAnythingToObjectiveC<A>(A) -> Swift.AnyObject", referenced from:
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () to @escaping @callee_guaranteed (@in_guaranteed Any?) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "type metadata for Swift.AnyObject", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "type metadata for Any", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      type metadata accessor for (Swift.String, Any) in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_encrypted_storage in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_encrypted_storage)
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_encrypted_storage in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_encrypted_storage)
  "_swift_bridgeObjectRelease", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      outlined destroy of Swift.DefaultStringInterpolation in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      outlined consume of Swift.String? in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      @objc react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned __C.NSString?, @unowned __C.NSString?, @unowned __C.NSError?) -> () to @escaping @callee_guaranteed (@guaranteed Swift.String?, @guaranteed Swift.String?, @guaranteed Swift.Error?) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      @objc react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      ...
  "_swift_bridgeObjectRetain", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.setItem(_: Swift.String, value: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      react_native_encrypted_storage.RNEncryptedStorage.removeItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      outlined copy of Swift.String? in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_dynamicCast", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_errorRelease", referenced from:
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned __C.NSString?, @unowned __C.NSString?, @unowned __C.NSError?) -> () to @escaping @callee_guaranteed (@guaranteed Swift.String?, @guaranteed Swift.String?, @guaranteed Swift.Error?) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_errorRetain", referenced from:
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned __C.NSString?, @unowned __C.NSString?, @unowned __C.NSError?) -> () to @escaping @callee_guaranteed (@guaranteed Swift.String?, @guaranteed Swift.String?, @guaranteed Swift.Error?) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_getForeignTypeMetadata", referenced from:
      type metadata accessor for __C.CFStringRef in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      type metadata accessor for __C.CFBooleanRef in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_getInitializedObjCClass", referenced from:
      type metadata accessor for react_native_encrypted_storage.RNEncryptedStorage in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_getObjCClassMetadata", referenced from:
      @objc static react_native_encrypted_storage.RNEncryptedStorage.requiresMainQueueSetup() -> Swift.Bool in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_getTupleTypeMetadata2", referenced from:
      type metadata accessor for (Swift.String, Any) in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_getWitnessTable", referenced from:
      lazy protocol witness table accessor for type Swift.String and conformance Swift.String : Swift.StringProtocol in Swift in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_release", referenced from:
      outlined consume of Foundation.Data._Representation in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      ___swift_destroy_boxed_opaque_existential_0 in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_retain", referenced from:
      outlined copy of Foundation.Data._Representation in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_unknownObjectRelease", referenced from:
      reabstraction thunk helper from @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () to @escaping @callee_guaranteed (@in_guaranteed Any?) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
      outlined destroy of Swift.AnyObject? in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
  "_swift_unknownObjectRetain", referenced from:
      react_native_encrypted_storage.RNEncryptedStorage.getItem(_: Swift.String, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-encrypted-storage.a(RNEncryptedStorage-f69d486c318e235f43d2bfa4bf4971f780a907c04080ff95bcee1149be7ba314.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the ****** editor. (in target '******' from project '******')

** BUILD FAILED **


The following build commands failed:
        Ld /Users/****/Library/Developer/Xcode/DerivedData/******-cvebcuqfadhsxpddapivjyinfxky/Build/Products/Debug-iphonesimulator/******.app/****** normal x86_64
(1 failure)
```
(obfuscated some info)

**Comment by emeraldsanto** [comment]
Is your project configured to use Swift? I might end up rewriting in Objective-C and Java to make the installation easier 🤔

**Comment by reddo** [comment]
Honestly, I'm not sure. I've just set the project up with `create-react-native-app`.

**Comment by emeraldsanto** [comment]
I see, I'll rewrite this in Objective-C and Java tonight and release a patch. That way there's no need to setup Swift and Kotlin support
